In [164]:
import pandas as pd
import requests
import json

### Beer Data by Style

In [165]:
# Load in the raw data

rawData = pd.read_csv('beers.csv')
rawData.head()

,Unnamed: 0,abv,ibu,id,name,style,brewery_id,ounces
0,0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0
1,1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0
3,3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0
4,4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0

In [166]:
# Filter beer data, get rid of columns that are not necessary

filteredBeer = rawData.drop(columns=['ibu','ounces','brewery_id'])
filteredBeer = filteredBeer.iloc[: , 1:]
filteredBeer.head()

     abv    id                 name                           style
0  0.050  1436             Pub Beer             American Pale Lager
1  0.066  2265          Devil's Cup         American Pale Ale (APA)
2  0.071  2264  Rise of the Phoenix                    American IPA
3  0.090  2263             Sinister  American Double / Imperial IPA
4  0.075  2262        Sex and Candy                    American IPA

In [167]:
# Figure out the unique styles of beer

list(set(filteredBeer['style']))

[nan,
 'Saison / Farmhouse Ale',
 'Roggenbier',
 'Bière de Garde',
 'Scotch Ale / Wee Heavy',
 'American Wild Ale',
 'Milk / Sweet Stout',
 'Cream Ale',
 'Other',
 'Quadrupel (Quad)',
 'Märzen / Oktoberfest',
 'American Barleywine',
 'Foreign / Export Stout',
 'Schwarzbier',
 'Dunkelweizen',
 'American Adjunct Lager',
 'Hefeweizen',
 'Light Lager',
 'Baltic Porter',
 'Braggot',
 'American Pilsner',
 'Oatmeal Stout',
 'Gose',
 'American Malt Liquor',
 'American Blonde Ale',
 'Shandy',
 'Maibock / Helles Bock',
 'American Porter',
 'American Pale Ale (APA)',
 'Scottish Ale',
 'Munich Dunkel Lager',
 'American Brown Ale',
 'American Black Ale',
 'English Bitter',
 'American Dark Wheat Ale',
 'English Stout',
 'Winter Warmer',
 'American Stout',
 'Mead',
 'Keller Bier / Zwickel Bier',
 'American Double / Imperial IPA',
 'English Barleywine',
 'Euro Dark Lager',
 'Dortmunder / Export Lager',
 'Rauchbier',
 'Altbier',
 'Rye Beer',
 'Vienna Lager',
 'Belgian IPA',
 'American Pale Wheat Ale',
 'Munich Helles Lager',
 'Belgian Strong Dark Ale',
 'Grisette',
 'English Brown Ale',
 'Bock',
 'English Pale Ale',
 'Russian Imperial Stout',
 'Czech Pilsener',
 'Euro Pale Lager',
 'American IPA',
 'Low Alcohol Beer',
 'Doppelbock',
 'German Pilsener',
 'American White IPA',
 'American India Pale Lager',
 'American Strong Ale',
 'Chile Beer',
 'American Double / Imperial Pilsner',
 'Belgian Dark Ale',
 'Old Ale',
 'American Pale Lager',
 'Kölsch',
 'California Common / Steam Beer',
 'Wheat Ale',
 'Irish Dry Stout',
 'Belgian Strong Pale Ale',
 'American Amber / Red Lager',
 'Herbed / Spiced Beer',
 'Abbey Single Ale',
 'Irish Red Ale',
 'English Pale Mild Ale',
 'Radler',
 'American Double / Imperial Stout',
 'Tripel',
 'Flanders Red Ale',
 'English Dark Mild Ale',
 'Smoked Beer',
 'American Amber / Red Ale',
 'Kristalweizen',
 'English Strong Ale',
 'Belgian Pale Ale',
 'Witbier',
 'Pumpkin Ale',
 'Extra Special / Strong Bitter (ESB)',
 'Dubbel',
 'Berliner Weissbier',
 'Flanders Oud Bruin',
 'Cider',
 'Fruit / Vegetable Beer',
 'English India Pale Ale (IPA)']

In [176]:
# Separating into specific flavor profiles - "crisp and clean"

crispFruit = ('Cream Ale', 'American Blonde Ale', 'Shandy', 'Czech Pilsener', 'American Pilsner', 'German Pilsener',
            'American India Pale Lager', 'Kolsch', 'Wheat Ale','Cider', 'Grissette')
crispMalt = ('Marzen / Oktoberfest', 'American Adjunct Lager', 'Light Lager', 'Maibock / Helles Bock', 
             'Munich Dunkel Lager', 'Dortmunder / Export Lager', 'Altbier', 'Vienna Lager', 'Munich Helles Lager', 
             'Bock','Doppelbock','Old Ale','American Amber / Red Lager', 'Radler', 'American Amber / Red Ale')
crispHop = ('Keller Bier / Zwickel Bier','Euro Pale Lager','American India Pale Lager', 
            'American Double / Imperial Pilsener', 'American Pale Lager')

# Creating dataframes that contains each of the "crisp and clean" flavors

cf = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(crispFruit)])
cm = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(crispMalt)])
ch = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(crispHop)])

In [177]:
# Next flavor profile - "hoppy and bitter"

hopEarth = ('English Bitter', 'American Double / Imperial IPA', 'Belgian IPA',
            'English Pale Ale', 'American IPA', 'American White IPA','Belgian Strong Pale Ale', 'Belgian Pale Ale', 
            'English India Pale Ale (IPA)')
hopMalt = ('Braggot', 'Mead', 'California Common / Steam Beer', "American Amber / Red Lager", 'American Barleywine')

he = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(hopEarth)])
hm = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(hopMalt)])

In [178]:
# Next flavor profile = "malty and sweet"

maltToast = ('Euro Dark Lager','English Brown Ale')
maltFruit = ('Biere de Garde', 'Scotch Ale / Wee Heavy', 'Scottish Ale', 'English Barleywine','Irish Red Ale',
             'Tripel', 'Extra Special / Strong Bitter (ESB)')

mt = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(maltToast)])
mf = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(maltFruit)])

In [179]:
# Next flavor profile = "dark and roasty"

darkSoft = ('Milk / Sweet Stout', 'Foreign / Export Stout', 'Schwarzbier', 'Baltic Porter', 'Oatmeal Stout',
       'American Porter', 'American Pale Ale (APA)', 'American Brown Ale', ' English Stout',
       'Winter Warmer', 'Dubbel')
darkDry = ('American Black Ale', 'American Stout', 'Russian Imperial Stout', 'American Double / Imperial Stout',
       'Irish Dry Stout', 'American Double / Imperial Stout')

ds = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(darkSoft)])
dd = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(darkDry)])

In [180]:
# Next flavor profile = "smoke"

smokeSmolder = tuple('Smoked Beer')
smokeMeat = tuple('Rauchbier')

sms = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(smokeSmolder)])
smm = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(smokeMeat)])

In [181]:
# Next flavor profile = "fruit and spice"

spiceBright = ('Saison / Farmhouse Ale', 'Roggenbier', 'Hefeweizen',
        'American Pale Wheat Ale','Herbed / Spiced Beer', 'English Pale Mild Ale',  'Kristalweizen', 'Witbier',
        'Pumpkin Ale', 'Belgian Blonde Ale', 'Tripel')
spiceDark = ('Quadrupel (Quad)', 'Dunkelweizen', 'American Dark Wheat Ale', 'Rye Beer', 'Belgian Strong Dark Ale',
             'English Dark Mild Ale', 'Dubbel')

spb = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(spiceBright)])
spd = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(spiceDark)])

In [182]:
# Next flavor profile = 'sour, tart, and funky'

sourDelicate = ('Gose','Berliner Weissbier')
sourFruity = ('Flanders Red Ale','Flanders Oud Bruin','Fruit / Vegetable Beer')
sourEarth = tuple('American Wild Ale')

sod = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(sourDelicate)])
sof = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(sourFruity)])
soe = pd.DataFrame(filteredBeer[filteredBeer['style'].isin(sourEarth)])

In [183]:
# Test run to try a beer! This will randomly select five beers from one of our narrowed down lists

sod.sample(n=5)

        abv    id                   name               style
1858  0.042  2479                 Jammer                Gose
716   0.050  2021      Here Gose Nothin'                Gose
1682  0.044  2370  18th Anniversary Gose                Gose
766   0.040  2283          Nomader Weiss  Berliner Weissbier
1346  0.043  2530              Daft Funk  Berliner Weissbier